services:

  qdrant:
    image: qdrant/qdrant:v1.18.2
    platform: linux/arm64
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API / dashboard
      - "6334:6334"  # gRPC API
    volumes:
      - ./.volumes/qdrant_data:/qdrant/storage


volumes:
  qdrant_data:
